### ISSUE TITLE
 Intermittent failure where 'AWSAccessKeyId' => 'AWSAccessKeyId'

### ISSUE THREAD

**Issue by mzehrer** [fleetfootmike/amazon-sqs-simple#13]
Is the bug from https://rt.cpan.org/Public/Bug/Display.html?id=95807 fixed here?

---

System: Ubuntu 14.04 trusty
Amazon::SQS::Simple from ubuntu package libamazon-sqs-simple-perl 2.03-1 
(our $VERSION   = '2.03';)

Using it to send messages only, it works fine most of the time but 
sometime I get the error:

ERROR [try ]: On calling SendMessage: 403 Forbidden (The AWS Access Key 
Id you provided does not exist in our records.)

If that's the case I notice that Amazon::SQS::Simple::Queue has wrong 
AWSAccessKeyId, here's dump of the object:

$VAR1 = bless({
   'SignatureVersion' => 2,
   'SecretKey' => 'correct secret key is here',
   'Version' => '2012-11-05',
   'Endpoint' => 'http://queue.amazonaws.com/089741050239 ...',
   'AWSAccessKeyId' => 'AWSAccessKeyId'
}, 'Amazon::SQS::Simple::Queue' );

AWSAccessKeyId is set to 'AWSAccessKeyId'. At first I thought I am doing 
something wrong but it's a pretty simple script that gets both aws 
access key and aws secret key from command line. I run it number of 
times and most of the time it does work but sometime it doesn't (in 
approximately 10% to 20% it does not work).

**Comment by fleetfootmike** [comment]
Fixed in 2.04 - it's an amusing issue surfaced by hash key randomisation :D

**Comment by fleetfootmike** [comment]
2.04 now on PAUSE, should be available from CPAN shortly.
